export enum ContractStatus {
  DRAFT = 'DRAFT',
  PENDING_TENANT = 'PENDING_TENANT',
  PENDING_LANDLORD = 'PENDING_LANDLORD',
  PENDING_BROKER = 'PENDING_BROKER',
  PENDING_KEBELE = 'PENDING_KEBELE',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  TERMINATED = 'TERMINATED',
  DISPUTED = 'DISPUTED',
}